# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Site settings
permalink: /:title.html
exclude:
  - "Makefile"
  - "README.md"
  - "CNAME"
  - "node_modules"
  - "vendor"
  - "Gemfile"
  - "Gemfile.lock"
sass:
  style: compressed

# Site info
url: https://ricostacruz.com/til
title: Today I Learned

# Google analytics
analytics:
  hostname: ricostacruz.com
  id: "UA-20473929-1"

# Collections
collections:
  - authors

# Default variables
defaults:
  -
    scope:
      path: ""
    values:
      layout: "article"
      tags: []
      secret: false
      author: Rico Sta. Cruz
