# This is a docker manifest for development, NOT production.
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    ports:
      - '25600:25600'
    command: ['bundle', 'exec', 'jekyll', 'serve', '--safe', '--watch', '--port', '25600', '--host', '0.0.0.0']

volumes:
  rubygems:
